name: project_timo
channels: 
- conda-forge
dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- simplegeneric
- rpy2

- pip
- pip:
    - stargazer
    - tabulate
    - tzlocal



